version: '3'
services:
  app:
    image: ghcr.io/legout/yahoo-symbols-downloader/yahoo-symbols-downloader:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - WEBSHARE_PROXIES_URL=${WEBSHARE_PROXIES_URL}
    volumes:
      - ./config:/app/config
      - logs:/app/logs
    command: start-scheduler --settings /app/config/settings.toml
volumes:
  logs:
