[parameters.download]
concurrency = 10
max_retries = 5
random_delay_multiplier = 10
random_proxy = true
random_user_agent = true
verbose = false

[parameters.run]
batch_size = 1_000
query_length = 2
types = [
  "equity",
  "etf",
  "mutualfund",
  "cryptocurrency",
  "index",
  "currency",
  "future"
]

[schedule]
cron = "30 23 * * 1,3,5"

  [schedule.logging]
  filename = "tasks"
  path = "logs"
  repo = "csv"

[storage]
type = "s3"

  [storage.local]
  bucket = "yfin-db"
  partitioning = "hive"
  path = "symbol-info"

  [storage.s3]
  bucket = "yfin-db"
  partitioning = "hive"
  path = "symbol-info"
  profile = "swfs"

  [storage.sqlite]
  path = "yfin-db/symbol-info.db"