---
parameters:
  download:
    concurrency: 10
    max_retries: 5
    random_delay_multiplier: 10
    random_proxy: true
    random_user_agent: true
    verbose: false
  run:
    batch_size: 1000
    query_length: 2
    types:
      - equity
      - etf
      - mutualfund
      - cryptocurrency
      - index
      - currency
      - future
schedule:
  cron: 30 23 * * 1,3,5
  logging:
    filename: tasks
    path: logs
    repo: csv # csv or sqlite (currently not working, use csv)
storage:
  local:
    bucket: yahoo-symbols
    partitioning: hive
    path: symbol-info
  s3:
    bucket: yahoo-symbols
    partitioning: hive
    path: symbol-info
    profile: storj
  sqlite:
    path: yahoo-symbols.db
  type: s3 # sqlite, local, s3