[parameters.download]
concurrency = 25
max_retries = 5
random_delay_multiplier = 2
random_proxy = true
random_user_agent = true
verbose = true
warnings = false
debug = false
proxies = ""

[parameters.run]
batch_size = 1_000
query_length = 2
types = [
  "equity",
  "etf",
  "mutualfund",
  "cryptocurrency",
  "index",
  "currency",
  "future",
]
log_path = "logs"

[parameters.scheduler]
cron = "47 3 * * 1-5"

[storage]
type = "s3"

[storage.local]
bucket = "yfin-db"
partitioning = "hive"
path = "symbol-info"

[storage.s3]
bucket = "yfin-db"
partitioning = "hive"
path = "symbol-info"
profile = ""

[storage.sqlite]
path = "yfin-db/symbol-info.db"
